name: Publish Python Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] # Runs only when a new tag starting with "v" is pushed

jobs:
  build-and-publish:
    name: Build and Publish Package
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build Wheels
        env:
          CXXFLAGS: "-std=c++11"
          CIBW_SKIP: "pypy*"
          CIBW_BUILD: "cp*"
        run: cibuildwheel --output-dir wheelhouse .
  
      - name: Upload Wheels Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python-version }}-${{ github.run_number }}
          path: wheelhouse/*.whl

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Verify uploaded package
        run: pip install --no-cache-dir --index-url https://pypi.org/simple/ your-package-name